eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost


microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: lb://PAYMENT-SERVICE/payment/doPayment

  order-service:
    endpoints:
      endpoint:
        url: lb://ORDER-SERVICE/order/bookOrder

logging:
  logback:
    rollingpolicy:
      max-file-size: 1MB
      file-name-pattern: /logs/archived/application-%d{yyyy-MM-dd}.%i.log
      max-history: 30
  file:
    name: /Users/ankitaggarwal/Downloads/Projects/logging/SpringJavaTechieE2E/microservice.log
  pattern:
    console: "%black(%d{ISO8601}) %c %highlight(%-5level) [%blue(%t)] %yellow(%C{1.}): %msg%n%throwable"
    file: "%d %c %-5level [%thread] %logger : %msg%n"
    level: "%5p"
  level:
    root: INFO
